### ISSUE TITLE
Rework normalizer 

### ISSUE THREAD

**Issue by Cryde** [Cryde/musicall#513]
Once reworked I will be able to set to true the serializer debug panel `config/packages/web_profiler.yaml:9` 
```
when@dev:
    framework:
        profiler:
            collect_serializer_data: false 
```

Reference issues : 
- https://github.com/symfony/symfony/discussions/47601
- https://github.com/symfony/maker-bundle/issues/1252
- https://github.com/symfony/symfony-docs/pull/16826#issuecomment-1151587036
